esp/esp/program/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('',
                       # manage stuff
                       (r'^manage/programs/?$', 'esp.program.views.manage_programs'),
                       (r'^manage/newprogram/?$', 'esp.program.views.newprogram'),
                       (r'^manage/submit_transaction/?$', 'esp.program.views.submit_transaction'),
                       (r'^manage/pages/?$', 'esp.program.views.manage_pages'),
                       (r'^manage/userview/?$', 'esp.program.views.userview'),
                       (r'^manage/usersearch/?$', 'esp.program.views.usersearch'),                       
                       (r'^manage/flushcache/?$', 'esp.program.views.flushcache'),
                       (r'^manage/statistics/?$', 'esp.program.views.statistics'),
                       (r'^manage/preview/?$', 'esp.program.views.template_preview'),
                       (r'^manage/mergeaccounts/?$', 'esp.users.views.merge.merge_accounts'),
                       )

esp/esp/urls.py
__author__    = "Individual contributors (see AUTHORS file)"
__date__      = "$DATE$"
__rev__       = "$REV$"
__license__   = "AGPL v.3"
__copyright__ = """
This file is part of the ESP Web Site
Copyright (c) 2007 by the individual contributors
  (see AUTHORS file)

The ESP Web Site is free software; you can redistribute it and/or
modify it under the terms of the GNU Affero General Public License
as published by the Free Software Foundation; either version 3
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public
License along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

Contact information:
MIT Educational Studies Program
  84 Massachusetts Ave W20-467, Cambridge, MA 02139
  Phone: 617-253-4882
  Email: esp-webmasters@mit.edu
Learning Unlimited, Inc.
  527 Franklin St, Cambridge, MA 02139
  Phone: 617-379-0178
  Email: web-team@lists.learningu.org
"""
import os
from django.conf.urls.defaults import patterns, include, handler500, handler404
from django.contrib import admin
from esp.settings import PROJECT_ROOT, MEDIA_ROOT

admin.autodiscover()

from esp.section_data import section_redirect_keys, section_prefix_keys

# Override error pages
handler404 = 'esp.web.util.main.error404'
handler500 = 'esp.web.util.main.error500'

# Static media
urlpatterns = patterns('django.views.static',
                       (r'^media/(?P<path>.*)$', 'serve', {'document_root': MEDIA_ROOT}),
                       (r'^admin/media/(?P<path>.*)$', 'serve', {'document_root': os.path.join(PROJECT_ROOT, 'admin/media/')}),
                       )

# Admin stuff
urlpatterns += patterns('',
                     (r'^admin/ajax_qsd/?', 'esp.qsd.views.ajax_qsd'),
                     (r'^admin/ajax_autocomplete/?', 'esp.db.views.ajax_autocomplete'),
                     (r'^admin/ajax_children/?', 'esp.datatree.views.ajax_children'),
                     (r'^admin/', include(admin.site.urls)),
                     (r'^accounts/login/$', 'esp.users.views.login_checked',),
                     #(r'^learn/Junction/2007_Spring/catalog/?$','django.views.generic.simple.redirect_to', {'url': '/learn/Junction/2007_Summer/catalog/'}),
                     (r'^(?P<subsection>(learn|teach|program|help|manage|onsite))/?$','django.views.generic.simple.redirect_to', {'url': '/%(subsection)s/index.html'} ),
                        )

#   Short term views
urlpatterns += patterns('',
                        (r'^', include('esp.shortterm.urls'),),
                        )


# generic stuff
urlpatterns += patterns('esp.web.views.main',
                        (r'^$', 'home'), # index
                        (r'^error_reporter', 'error_reporter'),
                        (r'^web$', 'home'), # index
                        (r'^esp_web', 'home'), # index
                        (r'.php$', 'home'), # index
                        )

# generic stuff
urlpatterns += patterns('django.views.generic',
                        (r'^web/?', 'simple.direct_to_template',{'template':'splash.html'}), # index
                        (r'^web$', 'simple.direct_to_template',{'template':'splash.html'}), # index                        
                        (r'^esp_web', 'simple.direct_to_template',{'template':'splash.html'}), # index
                        (r'.php$', 'simple.direct_to_template',{'template':'splash.html'}), # index                        
                        )

# program stuff
urlpatterns += patterns('',
                        (r'^',  include('esp.program.urls')),
                        )

urlpatterns += patterns('esp.web.views.bio',

                        # bios
                        (r'^(?P<tl>teach|learn)/teachers/(?P<last>[-A-Za-z0-9_ \.]+)/(?P<first>[-A-Za-z_ \.]+)(?P<usernum>[0-9]*)/bio.html$', 'bio'),
                        (r'^(?P<tl>teach|learn)/teachers/(?P<username>[^/]+)/bio.html$', 'bio'),
                        (r'^myesp/teacherbio/?$', 'bio_edit'),
                        (r'^(?P<tl>teach|learn)/teachers/(?P<last>[-A-Za-z0-9_ ]+)/(?P<first>[-A-Za-z_ ]+)(?P<usernum>[0-9]*)/bio.edit.html/?(.*)$', 'bio_edit'),
                        (r'^(?P<tl>teach|learn)/teachers/(?P<username>[^/]+)/bio.edit.html/?(.*)$', 'bio_edit'),
                        )

urlpatterns += patterns('',
                        (r'^myesp/', include('esp.users.urls'),)
                        )

urlpatterns += patterns('',
                        (r'^cache/', include('esp.cache.urls'),)
                        )

urlpatterns += patterns('esp.qsd.views',
                        (r'^(?P<subsection>(learn|teach|programs|manage|onsite))/(?P<url>.*).html$', 'qsd'),
                        (r'^(?P<url>.*)\.html$', 'qsd'),
                        )

#urlpatterns += patterns('',
#                        (r'^(?P<subsection>(learn|teach|programs|manage|onsite))/?$', 'django.views.generic.simple.redirect_to', {'url': '/%(subsection)s/index.html'} ),
#                        )

# logging in and out
urlpatterns += patterns('django.contrib.auth.views',
                     (r'^myesp/signout/?$', 'logout',{'next_page': '/myesp/signedout/'}),
                        )

# other apps
urlpatterns += patterns('',
#                        (r'^alumni/', include('esp.membership.alumni_urls')),
#                        (r'^membership/', include('esp.membership.urls')),
                        (r'^',  include('esp.miniblog.urls')),
                        (r'^',  include('esp.survey.urls')),
                        )

urlpatterns += patterns('esp.web.views.json',

     # JSON
    (r'json/teachers/$', 'teacher_lookup'))

# QSD Media
# aseering 8/14/2007: This ought to be able to be written in a simpler way...
urlpatterns += patterns('esp.web.views.main',

    # Possibly overspecific, possibly too general.
    (r'^(?P<subsection>(learn|teach|program|help))/(?P<url>.*)/qsdmedia/(?P<filename>[^/]+\.[^/]{1,4})$', 'redirect',
        { 'section_redirect_keys': section_redirect_keys, 'renderer': 'esp.qsdmedia.views.qsdmedia', 'section_prefix_keys': section_prefix_keys }),
    (r'^(?P<subsection>(learn|teach|program|help))/qsdmedia/(?P<filename>[^/]+\.[^/]{1,4})$', 'redirect',
        { 'section_redirect_keys': section_redirect_keys, 'renderer': 'esp.qsdmedia.views.qsdmedia', 'section_prefix_keys': section_prefix_keys, 'url': ''}),
    (r'^(?P<url>.*)/qsdmedia/(?P<filename>[^/]+\.[^/]{1,4})$', 'redirect',
        { 'section_redirect_keys': section_redirect_keys, 'renderer': 'esp.qsdmedia.views.qsdmedia' }),
    (r'^qsdmedia/(?P<filename>[^/]+\.[^/]{1,4})$', 'redirect',
        { 'section_redirect_keys': section_redirect_keys, 'renderer': 'esp.qsdmedia.views.qsdmedia', 'url': '' }),

    # aseering - Is it worth consolidating these?  Two entries for the single "contact us! widget
    # Contact Us! pages
    (r'^contact/contact/?$', 'contact'),
    (r'^contact/contact/(?P<section>[^/]+)/?$', 'contact'),
#    (r'^contact/submit.html$', 'contact_submit'),


    # Program stuff
    (r'^(onsite|manage|teach|learn|volunteer)/([-A-Za-z0-9_ ]+)/([-A-Za-z0-9_ ]+)/([-A-Za-z0-9_ ]+)/([-A-Za-z0-9_ ]+)/?$', 'program'),
    (r'^(onsite|manage|teach|learn|volunteer)/([-A-Za-z0-9_ ]+)/([-A-Za-z0-9_ ]+)/([-A-Za-z0-9_ ]+)/?$', 'program'),

    #??? (axiak)
    #(r'^program/Template/$', 'esp.program.views.programTemplateEditor'),
    #(r'^program/(?P<program>[-A-Za-z0-9_ ]+)/(?P<session>[-A-Za-z0-9_ ]+)/Classes/Template/$', 'esp.program.views.classTemplateEditor'),

    # all the archives
    (r'^archives/([-A-Za-z0-9_ ]+)/?$', 'archives'),
    (r'^archives/([-A-Za-z0-9_ ]+)/([-A-Za-z0-9_ ]+)/?$', 'archives'),
    (r'^archives/([-A-Za-z0-9_ ]+)/([-A-Za-z0-9_ ]+)/([-A-Za-z0-9_ ]+)/?$', 'archives'),
    (r'^myesp/([-A-Za-z0-9_ ]+)/?$', 'myesp'),

    # DB-generated QSD pages: HTML or plaintext
    #                        (r'^(?P<url>.*)\.html$', 'redirect', { 'section_redirect_keys': section_redirect_keys , 'renderer': qsd} ),
                        )
    
    # Event-generation
    # Needs to get fixed (axiak)
    #(r'^events/create/$', 'esp.cal.views.createevent'),
    #(r'^events/edit/$', 'esp.cal.views.updateevent'),
    #(r'^events/edit/(?P<id>\d+)/$', 'esp.cal.views.updateevent'),

urlpatterns += patterns('esp.web.views.navBar',
    # Update navbar
    (r'^navbar/edit.scm', 'updateNavBar') )

esp/esp/program/modules/forms/junction_teacher_review.py
from django import forms


choices = zip(range(11),range(11))

class JunctionTeacherReview(forms.Form):
    score = forms.ChoiceField(choices = choices,
                              help_text = '10 being best, 0 being worst')

    rejected = forms.BooleanField(required = False,
                                  help_text = 'If you want to reject them outright.')
    

esp/esp/program/modules/forms/mailinglabels_banzips.py
import django.forms as forms


class BanZipsForm(forms.Form):
    zips = forms.CharField(label="List of zip codes", widget=forms.Textarea(attrs={'cols':'20', 'rows':'40'}),
                           help_text="One on each line, zip+4 (e.g. 02139-4030 on one line)")

esp/esp/program/modules/forms/printables_refund.py
import django.forms as forms



class RefundInfoForm(forms.Form):
    payer_name = forms.CharField(help_text = 'The name from the credit card purchase.')
    payer_address = forms.CharField()
    userid = forms.CharField(widget=forms.HiddenInput)
    credit_card_num = forms.CharField(max_length=255, required=False, help_text="The CreditCard number used.")
    omars_number = forms.CharField(max_length=64, required=False, help_text="The number on OMARs form.")
    txn_amount = forms.CharField(max_length=10, required=False, help_text="The amount of money to refund, in case we don't have transaction data. (Please use only if you are VERY sure.)")
    

esp/esp/program/modules/forms/profile.py
from django import forms

class RemoteTeacherProfileForm(forms.ModelForm):
    volunteer = forms.BooleanField(required = False)
    need_bus = forms.BooleanField(required = False)

    def __init__(self, module=None, *args, **kwargs):
	self.base_fields['volunteer_times'] = forms.MultipleChoiceField(required = False, choices = module.getTimes())
	forms.ModelForm.__init__(self, *args, **kwargs)

    class Meta:
	from esp.program.modules.module_ext import RemoteProfile
	model = RemoteProfile
	fields = ('volunteer', 'need_bus', 'volunteer_times')

esp/esp/program/modules/forms/satprep.py
from django import forms

choice_tuples = (('diag', 'Diagnostic Exam'), ('prac', 'Practice Exam'))

class ScoreUploadForm(forms.Form):
    test = forms.ChoiceField(label='Type of SAT test', choices=choice_tuples)
    file = forms.Field(required=False, widget=forms.FileInput, label='Upload score file', help_text='Please use the specified comma-separated variable (CSV) format.')
    text = forms.CharField(required=False, label='Enter CSV scores directly', help_text='If you enter scores here, the file will be ignored.', widget=forms.Textarea(attrs={'rows': 10, 'cols': 50}))

class SATScoreField(forms.IntegerField):
    def __init__(self, *args, **kwargs):
	forms.IntegerField.__init__(self,
		min_value = 200, max_value = 800,
		widget = forms.TextInput({'size':3, 'maxlength':3}),
                error_messages = {'min_value':'The lowest SAT score is %(limit_value)s.', 'max_value':'The highest SAT score is %(limit_value)s.'},
		*args, **kwargs)


class SATPrepTeacherInfoForm(forms.ModelForm):
    sat_math = SATScoreField(required = False)
    sat_verb = SATScoreField(required = False)
    sat_writ = SATScoreField(required = False)
    mitid = forms.RegexField(regex = r'[0-9]{9}', max_length = 9, widget = forms.TextInput({'size':10, 'class':'required'}),
	    error_messages={'invalid':'Not a valid MIT id.'})

    def __init__(self, subjects=None, *args, **kwargs):
        self.base_fields['subject'] = forms.ChoiceField(choices = subjects, required = True, widget = forms.Select({'size':1, 'class':'required'}))
        super(SATPrepTeacherInfoForm, self).__init__(*args, **kwargs)

    class Meta:
	from esp.program.modules.module_ext import SATPrepTeacherModuleInfo
	model = SATPrepTeacherModuleInfo
	fields = ('sat_math', 'sat_verb', 'sat_writ', 'mitid', 'subject')


class SATPrepDiagForm(forms.ModelForm):
    diag_math_score = SATScoreField(required = False)
    diag_verb_score = SATScoreField(required = False)
    diag_writ_score = SATScoreField(required = False)
    prac_math_score = SATScoreField(required = False)
    prac_verb_score = SATScoreField(required = False)
    prac_writ_score = SATScoreField(required = False)
    class Meta:
	from esp.program.models import SATPrepRegInfo
	model = SATPrepRegInfo
	fields = ('diag_math_score', 'diag_verb_score', 'diag_writ_score', 'prac_math_score', 'prac_verb_score', 'prac_writ_score')

class SATPrepInfoForm(forms.ModelForm):
    old_math_score = SATScoreField(required = False)
    old_verb_score = SATScoreField(required = False)
    old_writ_score = SATScoreField(required = False)

    heard_by = forms.CharField(max_length = 128, required = False, widget = forms.TextInput({'size':24}))
    class Meta:
	from esp.program.models import SATPrepRegInfo
	model = SATPrepRegInfo
	fields = ('old_math_score', 'old_verb_score', 'old_writ_score', 'heard_by')

esp/esp/program/controller.py
__author__    = "Individual contributors (see AUTHORS file)"
__date__      = "$DATE$"
__rev__       = "$REV$"
__license__   = "AGPL v.3"
__copyright__ = """
This file is part of the ESP Web Site
Copyright (c) 2007 by the individual contributors
  (see AUTHORS file)

The ESP Web Site is free software; you can redistribute it and/or
modify it under the terms of the GNU Affero General Public License
as published by the Free Software Foundation; either version 3
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public
License along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

Contact information:
MIT Educational Studies Program
  84 Massachusetts Ave W20-467, Cambridge, MA 02139
  Phone: 617-253-4882
  Email: esp-webmasters@mit.edu
Learning Unlimited, Inc.
  527 Franklin St, Cambridge, MA 02139
  Phone: 617-379-0178
  Email: web-team@lists.learningu.org
"""
from esp.calendar.models import Event
from esp.program.models import Program, Class
from datetime import datetime



def GetCurrentPrograms(time=datetime.now()):
    """ Get all programs that are currently running

    Note that, for a program to be currently running, its top-level """
    return Program.objects.filter(programschedule__event__start__lt=time, programschedule__event__end__gt=time)

esp/esp/program/modules/views.py
__author__    = "Individual contributors (see AUTHORS file)"
__date__      = "$DATE$"
__rev__       = "$REV$"
__license__   = "AGPL v.3"
__copyright__ = """
This file is part of the ESP Web Site
Copyright (c) 2007 by the individual contributors
  (see AUTHORS file)

The ESP Web Site is free software; you can redistribute it and/or
modify it under the terms of the GNU Affero General Public License
as published by the Free Software Foundation; either version 3
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public
License along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

Contact information:
MIT Educational Studies Program
  84 Massachusetts Ave W20-467, Cambridge, MA 02139
  Phone: 617-253-4882
  Email: esp-webmasters@mit.edu
Learning Unlimited, Inc.
  527 Franklin St, Cambridge, MA 02139
  Phone: 617-379-0178
  Email: web-team@lists.learningu.org
"""

esp/templates/program/modules/checkboxes.html
<table style="text-align: center" align="center" width="400">
<tr><th>Steps for Registration</th><th>Done?</th></tr>
{% for module in modules %}
{% if module.isStep %}
<tr>
<td>{% if module.useTemplate %}
<a href="#module-{{ module.id }}" title="{{ module.module.link_title }}">
    {{ module.module.link_title }} 
    </a> <em>(below)</em>
{% else %}
    {% autoescape off %}{{ module.makeLink }}{% endautoescape %}
{% endif %}
{% if module.required_label %}<em>{{ module.required_label }}</em>{% else %}
    {% if not module.module.required %}{% if not module.hideNotRequired %} <em>(not required)</em> {% endif %}{% endif %}
{% endif %}
</td>
<td>{% if not module.useTemplate %}
<a href="{{ module.get_full_path }}">
{% else %}
<a href="#module-{{ module.id }}">
{% endif %}
{% with module.isCompleted as moduleCompleted %}
<img src="/media/images/{% if not moduleCompleted %}no{% endif %}checkmark.gif" 
    {% if moduleCompleted %}title="Done!" alt="Done!"{% else %}
    title="Not Done" alt="Not Done"{% endif %} class="nocheckmark" />
</a>
{% endwith %}
</td>
</tr>
{% endif %}
{% endfor %}
</table>

esp/templates/program/modules/manage_base.html
{% extends "main.html" %}

{% block title %}Program Administration{% endblock %}

{% load subsection %}
{% block subsection %}
{% autoescape off %}{{ "Program Management"|subsection }}{% endautoescape %}
{% endblock %}


{% block breadcrumbs %}
<div id="breadcrumbs">
<a href="/manage/{{ program.getUrlBase }}/main" 
   title="Back to program management.">Back to management.</a>
</div>
{% endblock %}

esp/templates/program/modules/progressbar.html
{% block stylesheets %}
    {{ block.super }}
    <link rel="stylesheet" href="/media/styles/progressbar.css" type="text/css" />
{% endblock %}

<table class="progressbar" align="center" width="400">
<tr>
<td><img src="/media/images/progress/left_fill.gif" /></td>
{% for module in modules %}
{% if module.isStep %}
{% with module.fillProgressBar as moduleCompleted %}
<td class="progress{% if moduleCompleted %}_fill{% endif %}">
{% if module.useTemplate %}
<a href="#module-{{ module.id }}">
{% else %}
<a href="{{ module.get_full_path }}">
{% endif %}
<img src="/media/images/progress/bar{% if moduleCompleted %}_fill{% endif %}.gif" 
    {% if moduleCompleted %}title="Done!" alt="Done!"{% else %}
    title="Not Done" alt="Not Done"{% endif %} /><br />
</a>
{% if module.useTemplate %}
<a href="#module-{{ module.id }}" title="{{ module.module.link_title }}">
    {{ module.module.link_title }} 
    </a> <em>(below)</em>
{% else %}
    {% autoescape off %}{{ module.makeLink }}{% endautoescape %}
{% endif %}
{% if module.required_label %}<em>{{ module.required_label }}</em>{% else %}
    {% if not module.module.required %}{% if not module.hideNotRequired %} <em>(not required)</em> {% endif %}{% endif %}
{% endif %}
</td>
{% endwith %}
{% endif %}
{% endfor %}
<td><img src="/media/images/progress/right{% if completedAll %}_fill{% endif %}.gif" /></td>
</tr>
</table>

esp/templates/program/modules/satprep_reg.html
{% extends "main.html" %}

{% block title %}Profile Editor{% endblock %}

{% block subsection_name %}Student Profile Editor{% endblock %}

{% block content %}

<style type="text/css">

.required { border: 2px solid black; }

.form_error { font-size: 80%; font-style: italic; color: #C00; }

label { font-family: Arial, Lucida, Helvetica, sans-serif; font-size: 0.8em; font-weight: normal;}
label.groupheader { font-size: 1.2em; font-weight: bold; }
#divmaintext table td { vertical-align: top; }

</style>
<br /><br />
<h2>Hi {{user.username}}!</h2>
<h2>Please tell us a bit about yourself!</h2>
(Boxed fields are required.)

{% if form.has_errors %}
<h2 style="color:red">Please fix the error{{ form.error_dict|pluralize }} in the form.<h2>
{% endif %}


<form action="{{request.path}}" method="post">{% csrf_token %}
<table cellpadding="2" align="center" border="0">

{% include "users/profiles/usercontact.html" %}

{% ifequal profiletype "student" %}
  {% include "users/profiles/studentinfo.html" %}
  {% include "users/profiles/guardiancontact.html" %}
  {% include "users/profiles/emergencycontact.html" %}
{% endifequal %}

{% ifequal profiletype "teacher" %}
  {% include "users/profiles/teacherinfo.html" %}
  {% include "users/profiles/emergencycontact.html" %}
{% endifequal %}

{% ifequal profiletype "educator" %}
  {% include "users/profiles/educatorinfo.html" %}
{% endifequal %}

{% ifequal profiletype "guardian" %}
  {% include "users/profiles/guardianinfo.html" %}
{% endifequal %}

</table>

<br />
<center><input type='submit' value='Update your Information!'></center>

<br />
</form>


{% endblock %}

esp/templates/program/modules/satprep_stureg.html
{% extends "main.html" %}

{% block title %}Profile Editor{% endblock %}

{% block stylesheets %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="/media/styles/forms.css" />
{% endblock %}

{% block subsection_name %}Student Profile Editor{% endblock %}

{% block content %}
<br /><br />
<h1>SAT Prep - Specific Information </h1>
<br />
<p> Please fill out the following short form to give us SATPrep-specific information. <br />
While none of this information is required, it will greatly enhance our ability to help you.</p>

<div id="program_form">
{% if form.errors %}
<h2 style="color:red">Please fix the error{{ form.errors|pluralize }} in the form.<h2>
{% endif %}


<form action="{{request.path}}" method="post">{% csrf_token %}
<table cellpadding="2" align="center" border="0">

<tr>
 <td><label for="id_old_math_score">Current SAT Math Score:<br />
       <small>(if available)</small></label></td>
 <td>{{ form.old_math_score }} {% if form.old_math_score.errors %}
   <br /><span class="form_error">{{ form.old_math_score.errors|join:", " }}</span>
   {% endif %}
 </td>
</tr>

<tr>
 <td><label for="id_old_verb_score">Current SAT Verbal Score:<br />
       <small>(if available)</small></label></td>
 <td>{{ form.old_verb_score }} {% if form.old_verb_score.errors %}
   <br /><span class="form_error">{{ form.old_verb_score.errors|join:", " }}</span>
   {% endif %}
 </td>
</tr>

<tr>
 <td><label for="id_old_writ_score">Current SAT Writing Score:<br />
       <small>(if available)</small></label></td>
 <td>{{ form.old_writ_score }} {% if form.old_writ_score.errors %}
   <br /><span class="form_error">{{ form.old_writ_score.errors|join:", " }}</span>
   {% endif %}
 </td>
</tr>

<tr>
 <td><label for="id_heard_by">How did you hear about SATPrep?</label></td>
 <td>{{ form.heard_by }} {% if form.heard_by.errors %}
   <br /><span class="form_error">{{ form.heard_by.errors|join:", " }}</span>
   {% endif %}
 </td>
</tr>
<tr>
<td colspan="2">
<center><input type="submit" class="fancybutton" value="Save SAT Prep Information"></center>
</td>
</tr>
</table>
</form>

</div>

{% endblock %}

esp/templates/program/modules/sowclass.html
<hr><br />

<p style="font-family: arial; font-size:130%; margin-left:10px; text-align: center"><b>Select Your {{one}} Classes</p></b></center>

{% include "users/student_schedule.html" %}